toDo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todoapp/', include ('todoapp.urls')),
    path('admin/', admin.site.urls),
]

todoapp/urls.py
from django.urls import path

from . import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/complete/', views.complete, name='complete'),
    path('add/', views.add, name='add'),
    path('<int:task_id>/update/', views.update, name='update'),
    path('<int:task_id>/delete/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.auth_login, name='login'),
    path('welcome/', views.welcome, name='welcome'),
]

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todoapp/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'title',
            'description',
        ]

todoapp/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect

from . models import Task

def index(request):
    task_list = Task.objects.order_by('-created')
    context = {
        'task_list': task_list,
    }
    return render(request, 'index.html', context)

def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, 'detail.html', {'task': task})


def complete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        complete_value = request.POST.get('complete')
        if complete_value == 'true':
            task.complete = True
        elif complete_value == 'false':
            task.complete = False
        task.save()
    return render(request, 'detail.html', {'task': task})

def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task(title=title, description=description)
        task.save()
        return render(request, 'detail.html', {'task': task})
    return render(request, 'add.html')


def update(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        complete = request.POST.get('complete')
        task.title = title
        task.description = description
        if complete == 'true':
            task.complete = True
        elif complete == 'false':
            task.complete = False
        task.save()
        return render(request, 'detail.html', {'task': task})
    return render(request, 'update.html', {'task': task})


def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        task.delete()
        task_list = Task.objects.order_by('-created')[:5]
        context = {
            'task_list': task_list,
        }
        return render(request, 'index.html', context)
    return render(request, 'delete.html', {'task': task})


def signup(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        user = User(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
        user.save()
        return render(request, 'index.html')
    return render(request, 'signup.html')


def auth_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        print('Received username:', username)
        print('Received password:', password)

        user = authenticate(username=username, password=password)
        print (user)
        if user:
            print('user is not none')
            login(request, user)
            return redirect('todoapp:welcome')
        else:
            messages.error(request, 'Invalid username or password.')
    print('auth_login called')
    return render(request, 'login.html')


def welcome(request):
    return render(request, 'welcome.html')

todoapp/templates/add.html
{% extends 'todoapp_base.html' %}
{% load static %}
{% block title %}Add a Task{% endblock %}
{% block content %}
    <div class="todolist">
        <h1>Add a Task</h1>
        <form action="{% url 'todoapp:add' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Add a Task</legend>
                <p>
                    <label for="title">Title:</label>
                    <input type="text" name="title" id="title" />
                </p>
                <p>
                    <label for="description">Description:</label>
                    <textarea name="description" id="description" rows="5" cols="50">
                    </textarea>
                </p>
            </fieldset>
            <input type="submit" value="Add" />
        </form>
    </div>
{% endblock %}

todoapp/templates/delete.html
{% extends 'todoapp_base.html' %}
{% load static %}
{% block title %}Delete a Task{% endblock %}
{% block content %}
    <div class="todolist">
        <h1>Delete a Task</h1>
        <form action="{% url 'todoapp:delete' task.task_id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Delete Task: {{ task.title }}</legend>
                <p>
                    <label for="title">Title:</label>
                    <input type="text" name="title" id="title" value="{{ task.title }}" readonly />
                </p>
                <p>
                    <label for="description">Description:</label>
                    <textarea name="description" id="description" rows="5" cols="50" readonly>
                        {{ task.description }}
                    </textarea>
                </p>
                <p>
                    <br><strong>Are you sure you want to delete this task?</strong>
                </p>
            </fieldset>
            <input type="submit" value="Yes—Delete" />
        </form>
    </div>
{% endblock %}

todoapp/templates/detail.html
{% extends 'todoapp_base.html' %}
{% load static %}
{% block title %} {{ task.title }} {% endblock %}
{% block content %}
<form action="{% url 'todoapp:complete' task.task_id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Task: {{ task.title }}</legend>
        <p><em>{{ task.description }}</em></p>
        {% if task.complete %}
            <input type="radio" name="complete" value="true" id="true" checked/>
            <label for="true">Task Completed</label><br />
            <input type="radio" name="complete" value="false" id="false" />
            <label for="false">Task Not Completed</label><br />
        {% else %}
            <input type="radio" name="complete" value="true" id="true" />
            <label for="true">Task Completed</label><br />
            <input type="radio" name="complete" value="false" id="false" checked/>
            <label for="false">Task Not Completed</label><br />
        {% endif %}
        <p class="remove-link">
            <a href="{% url 'todoapp:update' task.task_id %}"><span class="todo-detail">Update</span></a>
            <a href="{% url 'todoapp:delete' task.task_id %}"><span class="todo-detail">Delete</span></a>

    </fieldset>
    <input type="submit" value="Completed" />
</form>
{% endblock %}

todoapp/templates/index.html
{% extends 'todoapp_base.html' %}
{% load static %}


{% block title %}To-Do List{% endblock %}

{% block content %}
    <div class="todolist">
        <h1>Tasks</h1>
        {% if task_list %}
            <ul>
            {% for task in task_list %}
                <li>{{ task.title }}<a href="{% url 'todoapp:detail' task.task_id %}"><span class="todo-detail">View</span></a>
                <a href="{% url 'todoapp:update' task.task_id %}"><span class="todo-detail">Update</span></a>
                <a href="{% url 'todoapp:delete' task.task_id %}"><span class="todo-detail">Delete</span></a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No tasks are available.</p>
        {% endif %}
    </div>
{% endblock %}

todoapp/templates/login.html
{% extends 'todoapp_base.html' %}
{% load static %}
{% block title %}To-Do List: User Login{% endblock %}
{% block content %}

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <div class="todolist">
        <h1>User Login</h1>
        <form action="{% url 'todoapp:login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" /><br />
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" /><br />
            <input type="submit" value="Login" />
        </form>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    </div>
{% endblock %}

todoapp/templates/signup.html
{% extends 'todoapp_base.html' %}
{% load static %}

    {% block title %}To-Do List: User Sign Up{% endblock %}

    {% block content %}
    <div class="todolist">
        <h1>User Sign Up</h1>
        <form action="{% url 'todoapp:signup' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" /><br />
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" /><br />
            <label for="first_name">First Name:</label>
            <input type="text" name="first_name" id="first_name" /><br />
            <label for="last_name">Last Name:</label>
            <input type="text" name="last_name" id="last_name" /><br />
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" /><br />
            <input type="submit" value="Sign Up" />
        </form>
    </div>

    {% endblock %}

todoapp/templates/todoapp_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'styles/todoapp.css' %}">
    </head>
    <body>
    <div id="todo-topmenu">
        <a href="{% url 'todoapp:index' %}">All Tasks</a>
        <a href="{% url 'todoapp:add' %}">Add a Task</a>
        <a href="{% url 'todoapp:signup' %}">Sign Up</a>
    </div>
    {% block content %}
    {% endblock %}
    <div id="todo-footer">
        <p>To-Do List // Built on Django Framework by Tina Morlock &copy; 2023</p>
    </body>
</html>

todoapp/templates/update.html
{% extends 'todoapp_base.html' %}
{% load static %}
{% block title %}Update a Task{% endblock %}
{% block content %}
    <div class="todolist">
        <h1>Update a Task</h1>
        <form action="{% url 'todoapp:update' task.task_id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Update a Task</legend>
                <p>
                    <label for="title">Title:</label>
                    <input type="text" name="title" id="title" value="{{ task.title }}" />
                </p>
                <p>
                    <label for="description">Description:</label>
                    <textarea name="description" id="description" rows="5" cols="50">
                        {{ task.description }}
                    </textarea>
                </p>
                <p>
                    {% if task.complete %}
            <input type="radio" name="complete" value="true" id="true" checked/>
            <label for="true">Task Completed</label><br />
            <input type="radio" name="complete" value="false" id="false" />
            <label for="false">Task Not Completed</label><br />
        {% else %}
            <input type="radio" name="complete" value="true" id="true" />
            <label for="true">Task Completed</label><br />
            <input type="radio" name="complete" value="false" id="false" checked/>
            <label for="false">Task Not Completed</label><br />
        {% endif %}
                </p>
            </fieldset>
            <input type="submit" value="Update" />
        </form>
    </div>
{% endblock %}

todoapp/templates/welcome.html
{% extends 'todoapp_base.html' %}
{% load static %}

{% block title %}To-Do List{% endblock %}

{% block content %}
    <div class="todolist">
        <p>Welcome back, {{ user.first_name }}.</p>
        <p>Would you like to <a href="{% url 'todoapp:add' %}">add a new task?</a></p>
    </div>
{% endblock %}
```